# Node.js (TypeScript)
# Build a Node.js (TypeScript) project with yarn.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  APP_ID: express-mongoose-template
  PORT: 3000
  LOG_LEVEL: debug
  REQUEST_LIMIT: 100kb
  SESSION_SECRET: mySecret
  MONGODB_URI_TEST: mongodb://localhost:27017/express-mongoose-template-test
  OPENAPI_SPEC: /api/v1/spec

trigger:
  - master

pr:
  - master
  - releases/*

resources:
  containers:
    - container: mongo
      image: mongo
      ports:
        - 27017:27017

pool:
  vmImage: "ubuntu-latest"

services:
  mongo: mongo

steps:
  - script: |
      yarn install
      yarn compile
    displayName: "yarn install and compile"

  - script: yarn test:junit
    displayName: "yarn test:junit"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: "**/test-results.xml"
