openapi: 3.0.1
info:
  title: express-mongoose-template
  description: express-mongoose-template
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification
paths:
  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
          content: {}
    post:
      tags:
        - Examples
      description: Create a new example
      requestBody:
        description: an example
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExampleBody"
        required: true
      responses:
        201:
          description: Example created
  /users:
    get:
      tags:
        - Users
      description: Fetch all users
      responses:
        200:
          description: Returns all users
          content: {}
    post:
      tags:
        - Users
      description: Create a new user
      requestBody:
        description: an user
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserBody"
        required: true
      responses:
        201:
          description: User created
  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          description: The id of the example to retrieve
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Return the example with the specified id
          content: {}
        404:
          description: Example not found
          content: {}
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
  /users/{user_id}:
    put:
      tags:
        - Users
      requestBody:
        description: updated user model
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserBody"
        required: true
      parameters:
        - name: user_id
          in: path
          description: user_id to update
          required: true
          schema:
            type: integer
      responses:
        200:
          description: User_model
          content: {}
        404:
          description: User not found
          content: {}
    get:
      tags:
        - Get user by id
      parameters:
        - name: user_id
          in: path
          description: The id of the user to retrieve
          required: true
          schema:
            type: number
      responses:
        200:
          description: User_model
          content: {}
        404:
          description: Example not found
          content: {}
components:
  schemas:
    UserBody:
      title: user
      required:
        - username
        - first_name
        - last_name
        - email
        - password
      properties:
        user_id:
          type: number
        username:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        password:
          type: string
        address:
          type: string
        avatar:
          type: string
        reviews:
          type: array
          items:
            type: object
            properties:
              review_id:
                type: integer
              review:
                type: string
              rating:
                type: integer
              created_by:
                type: object
                properties:
                  reviewer_id:
                    type: number
                  username:
                    type: string
                  first_name:
                    type: string
                  last_name:
                    type: string
                  avatar:
                    type: string
    ExampleBody:
      title: example
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: no_stress

  # https://swagger.io/docs/specification/data-models/data-types/#array for more
